### ISSUE TITLE
readme code causes error

### ISSUE THREAD

**Issue by annieeby** [learn-co-curriculum/evaluating-regression-lines#10]
editing the graph.py file from mode = 'line' to 'lines' _did not_ fix the issue.

from graph import m_b_trace, plot, trace_values
from plotly.offline import iplot, init_notebook_mode
init_notebook_mode(connected=True)
data_trace = trace_values(x_values, y_values)
regression_trace = m_b_trace(regression_line['m'], regression_line['b'], x_values)
plot([regression_trace, data_trace])

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-14-27fa2a4a027c> in <module>()
      4 data_trace = trace_values(x_values, y_values)
      5 regression_trace = m_b_trace(regression_line['m'], regression_line['b'], x_values)
----> 6 plot([regression_trace, data_trace])

~/Flatiron Machine Learning/graph.py in plot(traces, layout)
     28 def plot(traces, layout = {}):
     29     if not isinstance(traces, list): raise TypeError('first argument must be a list.  Instead is', traces)
---> 30     plotly.offline.iplot({'data': traces, 'layout': layout})
     31 
     32 def build_layout(x_range = None, y_range = None, options = {}):

/anaconda3/lib/python3.6/site-packages/plotly/offline/offline.py in iplot(figure_or_data, show_link, link_text, validate, image, filename, image_width, image_height, config)
    337     config.setdefault('linkText', link_text)
    338 
--> 339     figure = tools.return_figure_from_figure_or_data(figure_or_data, validate)
    340 
    341     # Though it can add quite a bit to the display-bundle size, we include

/anaconda3/lib/python3.6/site-packages/plotly/tools.py in return_figure_from_figure_or_data(figure_or_data, validate_figure)
   1477 
   1478         try:
-> 1479             figure = Figure(**figure).to_dict()
   1480         except exceptions.PlotlyError as err:
   1481             raise exceptions.PlotlyError("Invalid 'figure_or_data' argument. "

/anaconda3/lib/python3.6/site-packages/plotly/graph_objs/_figure.py in __init__(self, data, layout, frames, skip_invalid)
    378             is invalid AND skip_invalid is False
    379         """
--> 380         super(Figure, self).__init__(data, layout, frames, skip_invalid)
    381 
    382     def add_area(

/anaconda3/lib/python3.6/site-packages/plotly/basedatatypes.py in __init__(self, data, layout_plotly, frames, skip_invalid)
    137         # ### Import traces ###
    138         data = self._data_validator.validate_coerce(data,
--> 139                                                     skip_invalid=skip_invalid)
    140 
    141         # ### Save tuple of trace objects ###

/anaconda3/lib/python3.6/site-packages/_plotly_utils/basevalidators.py in validate_coerce(self, v, skip_invalid)
   2096                     else:
   2097                         trace = self.class_map[trace_type](
-> 2098                             skip_invalid=skip_invalid, **v_copy)
   2099                         res.append(trace)
   2100                 else:

/anaconda3/lib/python3.6/site-packages/plotly/graph_objs/_scatter.py in __init__(self, arg, cliponaxis, connectgaps, customdata, customdatasrc, dx, dy, error_x, error_y, fill, fillcolor, groupnorm, hoverinfo, hoverinfosrc, hoverlabel, hoveron, hovertext, hovertextsrc, ids, idssrc, legendgroup, line, marker, mode, name, opacity, orientation, r, rsrc, selected, selectedpoints, showlegend, stackgaps, stackgroup, stream, t, text, textfont, textposition, textpositionsrc, textsrc, tsrc, uid, unselected, visible, x, x0, xaxis, xcalendar, xsrc, y, y0, yaxis, ycalendar, ysrc, **kwargs)
   2324         self['marker'] = marker if marker is not None else _v
   2325         _v = arg.pop('mode', None)
-> 2326         self['mode'] = mode if mode is not None else _v
   2327         _v = arg.pop('name', None)
   2328         self['name'] = name if name is not None else _v

/anaconda3/lib/python3.6/site-packages/plotly/basedatatypes.py in __setitem__(self, prop, value)
   2773             # ### Handle simple property ###
   2774             else:
-> 2775                 self._set_prop(prop, value)
   2776 
   2777         # Handle non-scalar case

/anaconda3/lib/python3.6/site-packages/plotly/basedatatypes.py in _set_prop(self, prop, val)
   3009                 return
   3010             else:
-> 3011                 raise err
   3012 
   3013         # val is None

/anaconda3/lib/python3.6/site-packages/plotly/basedatatypes.py in _set_prop(self, prop, val)
   3004         validator = self._validators.get(prop)
   3005         try:
-> 3006             val = validator.validate_coerce(val)
   3007         except ValueError as err:
   3008             if self._skip_invalid:

/anaconda3/lib/python3.6/site-packages/_plotly_utils/basevalidators.py in validate_coerce(self, v)
   1551             validated_v = self.vc_scalar(v)
   1552             if validated_v is None:
-> 1553                 self.raise_invalid_val(v)
   1554 
   1555             v = validated_v

/anaconda3/lib/python3.6/site-packages/_plotly_utils/basevalidators.py in raise_invalid_val(self, v)
    242             typ=type_str(v),
    243             v=repr(v),
--> 244             valid_clr_desc=self.description()))
    245 
    246     def raise_invalid_elements(self, invalid_els):

ValueError: 
    Invalid value of type 'builtins.str' received for the 'mode' property of scatter
        Received value: 'line'

    The 'mode' property is a flaglist and may be specified
    as a string containing:
      - Any combination of ['lines', 'markers', 'text'] joined with '+' characters
        (e.g. 'lines+markers')
        OR exactly one of ['none'] (e.g. 'none')

**Comment by LoreDirick** [comment]
@annieeby fixed it, thanks!
