### ISSUE TITLE
Evaluating regression lines

### ISSUE THREAD

**Issue by BGScoones** [learn-co-curriculum/evaluating-regression-lines#14]
The code for the m_b_trace function that is imported in from a previous lesson is incorrect.

The m_b_trace code for that lesson is as follows:
def m_b_trace(m, b, x_values, mode = '**line**', name = 'line function'):
    values = m_b_data(m, b, x_values)
    values.update({'mode': mode, 'name': name})
    return values

Running this raises the following error:

ValueError: 
    Invalid value of type 'builtins.str' received for the 'mode' property of scatter
        Received value: 'line'

    The 'mode' property is a flaglist and may be specified
    as a string containing:
      - Any combination of ['lines', 'markers', 'text'] joined with '+' characters
        (e.g. 'lines+markers')
        OR exactly one of ['none'] (e.g. 'none')

This can be fixed by altering the code to the following:
def m_b_trace(m, b, x_values, mode = '**lines**', name = 'line function'):
    values = m_b_data(m, b, x_values)
    values.update({'mode': mode, 'name': name})
    return values

But this needs to be done manually in the evaluating regression lines lesson. The code for m_b_data function also needs to be manually input rather than imported as the lesson suggests.

**Comment by LoreDirick** [comment]
Fixed, thanks!
