### ISSUE TITLE
Error message from provided code

### ISSUE THREAD

**Issue by L-Lewis** [learn-co-curriculum/evaluating-regression-lines#16]
From this pre-written code towards the top of the lesson: `from graph import m_b_trace, plot, trace_values
from plotly.offline import iplot, init_notebook_mode
init_notebook_mode(connected=True)
data_trace = trace_values(x_values, y_values)
regression_trace = m_b_trace(regression_line['m'], regression_line['b'], x_values)
plot([regression_trace, data_trace])`

I get the following error message (on Chrome v70.0.3538.110, Windows 10) and am unable to produce the graph:
ValueErrorTraceback (most recent call last)
<ipython-input-4-27fa2a4a027c> in <module>()
      4 data_trace = trace_values(x_values, y_values)
      5 regression_trace = m_b_trace(regression_line['m'], regression_line['b'], x_values)
----> 6 plot([regression_trace, data_trace])

~/evaluating-regression-lines-data-science-intro-000/graph.py in plot(traces, layout)
     28 def plot(traces, layout = {}):
     29     if not isinstance(traces, list): raise TypeError('first argument must be a list.  Instead is', traces)
---> 30     plotly.offline.iplot({'data': traces, 'layout': layout})
     31 
     32 def build_layout(x_range = None, y_range = None, options = {}):

/opt/conda/envs/learn-env/lib/python3.6/site-packages/plotly/offline/offline.py in iplot(figure_or_data, show_link, link_text, validate, image, filename, image_width, image_height, config)
    334     config.setdefault('linkText', link_text)
    335 
--> 336     figure = tools.return_figure_from_figure_or_data(figure_or_data, validate)
    337 
    338     # Though it can add quite a bit to the display-bundle size, we include

/opt/conda/envs/learn-env/lib/python3.6/site-packages/plotly/tools.py in return_figure_from_figure_or_data(figure_or_data, validate_figure)
   1467 
   1468         try:
-> 1469             figure = Figure(**figure).to_dict()
   1470         except exceptions.PlotlyError as err:
   1471             raise exceptions.PlotlyError("Invalid 'figure_or_data' argument. "

/opt/conda/envs/learn-env/lib/python3.6/site-packages/plotly/graph_objs/_figure.py in __init__(self, data, layout, frames)
    312                         respective traces in the data attribute
    313         """
--> 314         super(Figure, self).__init__(data, layout, frames)
    315 
    316     def add_area(

/opt/conda/envs/learn-env/lib/python3.6/site-packages/plotly/basedatatypes.py in __init__(self, data, layout_plotly, frames)
    114 
    115         # ### Import traces ###
--> 116         data = self._data_validator.validate_coerce(data)
    117 
    118         # ### Save tuple of trace objects ###

/opt/conda/envs/learn-env/lib/python3.6/site-packages/_plotly_utils/basevalidators.py in validate_coerce(self, v)
   1953                         invalid_els.append(v_el)
   1954                     else:
-> 1955                         trace = self.class_map[trace_type](**v_copy)
   1956                         res.append(trace)
   1957                 else:

/opt/conda/envs/learn-env/lib/python3.6/site-packages/plotly/graph_objs/_scatter.py in __init__(self, arg, cliponaxis, connectgaps, customdata, customdatasrc, dx, dy, error_x, error_y, fill, fillcolor, hoverinfo, hoverinfosrc, hoverlabel, hoveron, hovertext, hovertextsrc, ids, idssrc, legendgroup, line, marker, mode, name, opacity, r, rsrc, selected, selectedpoints, showlegend, stream, t, text, textfont, textposition, textpositionsrc, textsrc, tsrc, uid, unselected, visible, x, x0, xaxis, xcalendar, xsrc, y, y0, yaxis, ycalendar, ysrc, **kwargs)
   2083         self.marker = marker if marker is not None else _v
   2084         _v = arg.pop('mode', None)
-> 2085         self.mode = mode if mode is not None else _v
   2086         _v = arg.pop('name', None)
   2087         self.name = name if name is not None else _v

/opt/conda/envs/learn-env/lib/python3.6/site-packages/plotly/basedatatypes.py in __setattr__(self, prop, value)
   2691                 prop in self._validators):
   2692             # Let known properties and private properties through
-> 2693             super(BasePlotlyType, self).__setattr__(prop, value)
   2694         else:
   2695             # Raise error on unknown public properties

/opt/conda/envs/learn-env/lib/python3.6/site-packages/plotly/graph_objs/_scatter.py in mode(self, val)
    828     @mode.setter
    829     def mode(self, val):
--> 830         self['mode'] = val
    831 
    832     # name

/opt/conda/envs/learn-env/lib/python3.6/site-packages/plotly/basedatatypes.py in __setitem__(self, prop, value)
   2663             # ### Handle simple property ###
   2664             else:
-> 2665                 self._set_prop(prop, value)
   2666 
   2667         # Handle non-scalar case

/opt/conda/envs/learn-env/lib/python3.6/site-packages/plotly/basedatatypes.py in _set_prop(self, prop, val)
   2893         # ------------
   2894         validator = self._validators.get(prop)
-> 2895         val = validator.validate_coerce(val)
   2896 
   2897         # val is None

/opt/conda/envs/learn-env/lib/python3.6/site-packages/_plotly_utils/basevalidators.py in validate_coerce(self, v)
   1506             validated_v = self.vc_scalar(v)
   1507             if validated_v is None:
-> 1508                 self.raise_invalid_val(v)
   1509 
   1510             v = validated_v

/opt/conda/envs/learn-env/lib/python3.6/site-packages/_plotly_utils/basevalidators.py in raise_invalid_val(self, v)
    214             typ=type_str(v),
    215             v=repr(v),
--> 216             valid_clr_desc=self.description()))
    217 
    218     def raise_invalid_elements(self, invalid_els):

ValueError: 
    Invalid value of type 'builtins.str' received for the 'mode' property of scatter
        Received value: 'line'

    The 'mode' property is a flaglist and may be specified
    as a string containing:
      - Any combination of ['lines', 'markers', 'text'] joined with '+' characters
        (e.g. 'lines+markers')
        OR exactly one of ['none'] (e.g. 'none')

**Comment by LoreDirick** [comment]
@L-Lewis  fixed it, thanks!
