### ISSUE TITLE
error un functions line_function_trace and m_b_trace

### ISSUE THREAD

**Issue by AnnaLara** [learn-co-curriculum/evaluating-regression-lines#19]
In:    evaluating-regression-lines/graph.py:

line 10:   def line_function_trace(line_function, x_values, mode = 'line', name = 'line function')
Instead of:   mode = 'line'
should be:   mode = 'lines'

line 23:   def m_b_trace(m, b, x_values, mode = 'line', name = 'line function')
Instead of:   mode = 'line'
should be:   mode = 'lines'

**Comment by LoreDirick** [comment]
@AnnaLara fixed, thanks!
