### ISSUE TITLE
Intro to RSS

### ISSUE THREAD

**Issue by jjacisin** [learn-co-curriculum/evaluating-regression-lines#5]
Hello! 

I think there's an error with one of the example formulas in the "Sigma Notation" lesson. In the section on 'Calculating and representing total error,' the RSS that illustrates the difference between the y and ŷ of the given points shows the wrong inputs for y₀. Currently, the full formula shows (apologies for the lack of formatting): 

RSS=(0−0)2+(150−250)2+(600−400)2+(700−700)2

I believe the first parenthesis should be updated to (100-100)2.  Please let me know if I'm missing something! 

Thanks!
Jim Jacisin

**Comment by sherzyang** [comment]
I agree, I think first parenthesis does need to be updated to (100-100)^2
