### ISSUE TITLE
Function Syntax Errors

### ISSUE THREAD

**Issue by rwilley83** [learn-co-curriculum/evaluating-regression-lines#6]
File: evaluating-regression-lines/graph.py

def line_function_trace(line_function, x_values, mode = 'line', name = 'line function'):
    values = line_function_data(line_function, x_values)
    values.update({'mode': mode, 'name': name})
    return values

def m_b_trace(m, b, x_values, mode = 'line', name = 'line function'):
    values = m_b_data(m, b, x_values)
    values.update({'mode': mode, 'name': name})
    return values

(mode = 'line') should be (mode = 'lines')

**Comment by LoreDirick** [comment]
@rwilley83 Fixed, thanks!
