### ISSUE TITLE
Error in plotting regression line

### ISSUE THREAD

**Issue by ssmithie** [learn-co-curriculum/evaluating-regression-lines#7]
it looks like m_b_trace is taking in mode = 'line' instead of mode = 'lines'

ValueError: 
    Invalid value of type 'builtins.str' received for the 'mode' property of scatter
        Received value: 'line'

    The 'mode' property is a flaglist and may be specified
    as a string containing:
      - Any combination of ['lines', 'markers', 'text'] joined with '+' characters
        (e.g. 'lines+markers')
        OR exactly one of ['none'] (e.g. 'none')

**Comment by LoreDirick** [comment]
@ssmithie Fixed, thanks!
