### ISSUE TITLE
ValueError from the provided code

### ISSUE THREAD

**Issue by Socjon** [learn-co-curriculum/evaluating-regression-lines#9]
When shift+entering the example coding, I received a value error.

> ValueError: 
>     Invalid value of type 'builtins.str' received for the 'mode' property of scatter
>         Received value: 'line'
> 
>     The 'mode' property is a flaglist and may be specified
>     as a string containing:
>       - Any combination of ['lines', 'markers', 'text'] joined with '+' characters
>         (e.g. 'lines+markers')
>         OR exactly one of ['none'] (e.g. 'none')

It came from trying to plot the regression line. This was the code provided.

`from graph import m_b_trace, plot, trace_values
from plotly.offline import iplot, init_notebook_mode
init_notebook_mode(connected=True)
data_trace = trace_values(x_values, y_values)
regression_trace = m_b_trace(regression_line['m'], regression_line['b'], x_values)
plot([regression_trace, data_trace])`

Thanks for any help looking into this matter.

**Comment by LoreDirick** [comment]
@Socjon fixed, thanks!
